// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: opts.proto

package gotags

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Opts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kvs []string `protobuf:"bytes,1,rep,name=kvs,proto3" json:"kvs,omitempty"`
}

func (x *Opts) Reset() {
	*x = Opts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Opts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Opts) ProtoMessage() {}

func (x *Opts) ProtoReflect() protoreflect.Message {
	mi := &file_opts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Opts.ProtoReflect.Descriptor instead.
func (*Opts) Descriptor() ([]byte, []int) {
	return file_opts_proto_rawDescGZIP(), []int{0}
}

func (x *Opts) GetKvs() []string {
	if x != nil {
		return x.Kvs
	}
	return nil
}

var file_opts_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: ([]*Opts)(nil),
		Field:         9000,
		Name:          "go.tags.opts",
		Tag:           "bytes,9000,rep,name=opts",
		Filename:      "opts.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// repeated go.tags.Opts opts = 9000;
	E_Opts = &file_opts_proto_extTypes[0]
)

var File_opts_proto protoreflect.FileDescriptor

var file_opts_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6f, 0x70, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x6f,
	0x2e, 0x74, 0x61, 0x67, 0x73, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x18, 0x0a, 0x04, 0x4f, 0x70, 0x74, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x76, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x76,
	0x73, 0x3a, 0x41, 0x0a, 0x04, 0x6f, 0x70, 0x74, 0x73, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xa8, 0x46, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x67, 0x6f, 0x2e, 0x74, 0x61, 0x67, 0x73, 0x2e, 0x4f, 0x70, 0x74, 0x73, 0x52, 0x04,
	0x6f, 0x70, 0x74, 0x73, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x67,
	0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x67, 0x6f, 0x74, 0x61, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_opts_proto_rawDescOnce sync.Once
	file_opts_proto_rawDescData = file_opts_proto_rawDesc
)

func file_opts_proto_rawDescGZIP() []byte {
	file_opts_proto_rawDescOnce.Do(func() {
		file_opts_proto_rawDescData = protoimpl.X.CompressGZIP(file_opts_proto_rawDescData)
	})
	return file_opts_proto_rawDescData
}

var file_opts_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_opts_proto_goTypes = []interface{}{
	(*Opts)(nil),                      // 0: go.tags.Opts
	(*descriptorpb.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
}
var file_opts_proto_depIdxs = []int32{
	1, // 0: go.tags.opts:extendee -> google.protobuf.FieldOptions
	0, // 1: go.tags.opts:type_name -> go.tags.Opts
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_opts_proto_init() }
func file_opts_proto_init() {
	if File_opts_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_opts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Opts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_opts_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_opts_proto_goTypes,
		DependencyIndexes: file_opts_proto_depIdxs,
		MessageInfos:      file_opts_proto_msgTypes,
		ExtensionInfos:    file_opts_proto_extTypes,
	}.Build()
	File_opts_proto = out.File
	file_opts_proto_rawDesc = nil
	file_opts_proto_goTypes = nil
	file_opts_proto_depIdxs = nil
}
